app:
  applicationId: "GENERADO_EN_RUNTIME"
  env: ci
  host: http://localhost:8080
  paths:
    - /
 
hawk:
  failureThreshold: high
  spider:
    maxDuration: 2
    ajaxSpider: false
  scan:
    maxDuration: 10